# Generated by Django 3.0.1 on 2020-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_title', models.CharField(max_length=200)),
                ('tut_content', models.TextField()),
                ('date_published', models.DateTimeField()),
            ],
        ),
    ]
